/**
 * Notes:
 * favicon is an svg of the state/city/county etc
 * 
 */

import React from 'react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import DonationHeader from '@/components/DonationHeader'
import NavigationBar from '@/components/NavigationBar'
import Footer from '@/components/Footer'
import DonationElement from '@/components/DonationElement'
import JoinUs from '@/components/JoinUs'
import Twitter from '@/components/Twitter'
import TakeAction from '@/components/TakeAction'
import AboutTeaser from '@/components/AboutTeaser'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children, pageTitle, imageUrl, hideAbout, hidePolicies, hideDonation, hideJoinUs, hideTwitter, hideAll }) => {
    const defaultImageUrl = '';
    const finalImageUrl = imageUrl || defaultImageUrl;
  
    return (
      <main>
            <Head>
                <title>{`${pageTitle} - CAMPAIGN_NAME`}</title>
                <meta name="description" content="DATA" />
                <link rel="icon" href="FAVICON" />
                <link rel='canonical' href='WEBSITE_URL' />
                <meta property="og:type" content="website" />
                <meta property="og:url" content="WEBSITE_URL" />
                <meta property="og:description" content="DATA" />
                <meta
                    property="og:image"
                    content={finalImageUrl}
                    />
                <meta name="og:title" content={`CAMPAIGN_NAME - ${pageTitle}`} />
                <meta name="twitter:card" content="summary_large_image" />  
            </Head>

            <div className=''>
            <NavigationBar/>
              <div className=''>
                <div className='h-[65px]' alt='spacer'></div>
                {children}
              </div>

            { !hideAbout  && <AboutTeaser/> }
            { !hidePolicies  && <TakeAction/> }  
            { !hideDonation  && <DonationElement/> }  
            { !hideJoinUs && <JoinUs/> }  
              {/*<Twitter/>*/}
              <Footer/>
            </div>

      </main>
    )
  }
  
  export default RootLayout
  